### ISSUE TITLE
interact bugs under draggable and resizable when using css transform

### ISSUE THREAD

**Issue by munkex** [taye/interact.js#400] opened 2016-07-06 14:13 UTC
We have been using your interact js for quit some time now, and we have now tried to implement a feature where out users are able to zoom the canvas.
When we use javascript to zoom content with transform/ scale and -ms-zoom interact starts to act wierd

This is the stuff we use to zoom the  canvas width:
$(".zoomContent").css("transform", "scale("+zoomLevel+")").css("-ms-zoom", "scale("+zoomLevel+")").css("-webkit-transform", "scale("+zoomLevel+")").css("-moz-transform", "scale("+zoomLevel+")");

If we zoom under 100% of the normal size (1920x1080px) resizable start to jump around and wont fit to edges and starts to be 1059.10px instead of 1060px wide..

also draggable wont fit to edges and stops in the middle of the canvas so we aint able to drag it any further..

**Comment by taye** [comment] 2016-08-10 12:33
Duplicate of #137.

**Closed by taye** 2016-08-10 12:33 UTC
