### ISSUE TITLE
Interact .draggable and webcomponentsjs conflict in IE

### ISSUE THREAD

**Issue by radiart** [taye/interact.js#310] opened 2015-11-11 16:36 UTC
Hi I have problem when using webcomponentsjs (https://github.com/webcomponents/webcomponentsjs) with Interact draggable function under IE 10 and 11

``		.draggable({
		  // enable inertial throwing
		  inertia: true,
		  // keep the element within the area of it's parent
		  restrict: {
			restriction: "parent",
			endOnly: true,
			elementRect: { top: 0, left: 0, bottom: 1, right: 1 }
		  }, ``

I getting such error:

``SCRIPT5078: Cannot redefine non-configurable property 'defaultPrevented'
File: webcomponents-lite.js, Line: 1039, Column: 7``

...any ideas?

**Comment by taye** [comment] 2015-11-11 16:40
Can you paste or upload a screenshot of a full stack trace?

Am 11/11/15 um 16:36 schrieb Rafał Radomski:

**Comment by radiart** [comment] 2015-11-11 16:48
You meant something like that? Recreate whole use case can be difficult...

``	interact('#noteTool .resize-drag')
		.resizable({
		  edges: { left: true, right: true, bottom: true, top: true },
		  restrict: {
			restriction: "parent"
		  },
		  onstart: function (event) {
			vm.resizeNote = true;
		  },
		  onend: function (event) {
			resizeQuill();
		  }
		})
		.on('resizemove', listenerResize)
		.draggable({
		  // enable inertial throwing
		  inertia: true,
		  // keep the element within the area of it's parent
		  restrict: {
			restriction: "parent",
			endOnly: true,
			elementRect: { top: 0, left: 0, bottom: 1, right: 1 }
		  },

		  // call this function on every dragmove event
		  onmove: dragMoveListener,
		  onstart: function(event) {
			 //
		  },
		  // call this function on every dragend event
		  onend: function (event) {
			var textEl = event.target.querySelector('p');

			textEl && (textEl.textContent =
				'moved a distance of '
				+ (Math.sqrt(event.dx * event.dx +
					event.dy * event.dy)|0) + 'px');
		  }
		})
		.on('resizemove', function (event) {
		  var target = event.target,
			  x = (parseFloat(target.getAttribute('data-x')) || 0),
			  y = (parseFloat(target.getAttribute('data-y')) || 0);

		  // update the element's style
		  target.style.width  = event.rect.width + 'px';
		  target.style.height = event.rect.height + 'px';

		  // translate when resizing from top or left edges
		  x += event.deltaRect.left;
		  y += event.deltaRect.top;

		  target.style.webkitTransform = target.style.transform =
			  'translate(' + x + 'px,' + y + 'px)';

		  target.setAttribute('data-x', x);
		  target.setAttribute('data-y', y);
		});

	function listenerResize() {
	 //
	}

	function dragMoveListener (event) {
	  var target = event.target,
	  // keep the dragged position in the data-x/data-y attributes
		  x = (parseFloat(target.getAttribute('data-x')) || 0) + event.dx,
		  y = (parseFloat(target.getAttribute('data-y')) || 0) + event.dy;

	  // translate the element
	  target.style.webkitTransform =
		  target.style.transform =
			  'translate(' + x + 'px, ' + y + 'px)';

	  // update the posiion attributes
	  target.setAttribute('data-x', x);
	  target.setAttribute('data-y', y);
	}

	window.dragMoveListener = dragMoveListener; ``

**Comment by taye** [comment] 2015-11-11 16:51
No, I meant expand the error in the console to see all the function 
calls that lead to the error.

Am 11/11/15 um 16:48 schrieb Rafał Radomski:

**Comment by radiart** [comment] 2015-11-11 16:55
![Error](http://oi68.tinypic.com/2r6yzdf.jpg)

**Comment by taye** [comment] 2015-11-11 17:07
No, not that either. It should show the "call stack" or "stack trace" from where the error occured. On Chrome, this is what they look like:

![bildschirmfoto von 2015-11-11 17-02-24](https://cloud.githubusercontent.com/assets/1679746/11097238/3c974978-8896-11e5-9f27-38ede77a24fd.png)
![bildschirmfoto von 2015-11-11 17-02-47](https://cloud.githubusercontent.com/assets/1679746/11097237/3c9350a2-8896-11e5-9033-15bb496c70b6.png)

Either one of those would be helpful.

**Comment by radiart** [comment] 2015-11-12 09:52
@taye try run this on IE: https://jsfiddle.net/ynxuy50g/1/ and drag the green div

**Comment by taye** [comment] 2015-11-12 10:53
I don't have access to IE10/11 right now. Here is some more info on using the IE debugger: https://msdn.microsoft.com/en-us/library/dn255006%28v=vs.85%29.aspx. Run `console.ltrace()` in the console when the debugger is paused at the error to get a stack trace

I'm closing this issue until you can you can provide a stack trace. The issue is most likely a problem with webcomponets, not interact.js.

**Closed by taye** 2015-11-12 10:53 UTC

**Comment by radiart** [comment] 2015-11-12 11:22
console.trace()
   at eval code (eval code:1:1)
   at eval code (eval code:29:29)
   at Event.prototype.preventDefault (https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.16/webcomponents-lite.js:1039:7)
   at Interaction.prototype.checkAndPreventDefault (https://cdnjs.cloudflare.com/ajax/libs/interact.js/1.2.6/interact.js:3140:17)
   at Interaction.prototype.pointerMove (https://cdnjs.cloudflare.com/ajax/libs/interact.js/1.2.6/interact.js:1929:21)
   at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/interact.js/1.2.6/interact.js:3348:17)

**Comment by taye** [comment] 2015-11-12 11:40
The problem is in the webcomponents polyfill. You should report it to them if you haven't already done so.
