### ISSUE TITLE
Cursor stuck on move/resize

### ISSUE THREAD

**Issue by eveningforgery** [taye/interact.js#536] opened 2017-08-04 14:54 UTC
### Actual behavior
On a simple click without moving at all, the cursor is stuck into what it was before clicking.
You can replicate this bug on your own demos: http://interactjs.io/

### Expected behavior
The cursor should have been reseted to default.

### System configuration
**interact.js 1.2.9**
**Chrome 59.0.3071.115 & Firefox 54**:
**MacOS Sierra 10.12.3 & Windows 10**:

**Comment by zuzusik** [comment] 2017-08-14 19:26
Reproducible for me too

**Comment by zuzusik** [comment] 2017-08-14 19:41
Can be fixed by disabling cursor styling with calling `.styleCursor(false)`

**Comment by DrSensor** [comment] 2017-12-23 06:21
I have the same problem especially in draggable when implemented using context 
`interact('*', { context: myDiv}).draggable()`

**Comment by taye** [comment] 2018-02-16 00:54
I'm closing this as the issue is fixed in v1.3 and v1.4.0-alpha. In these versions, after releasing the mouse button, the cursor style is cleared until the next move or down event.

**Closed by taye** 2018-02-16 00:54 UTC
