### ISSUE TITLE
Scrolling Drop Issue

### ISSUE THREAD

**Issue by kgibb** [taye/interact.js#491] opened 2017-01-31 17:10 UTC
Hi, I've implemented a reorder-able list. Drag is initiated via a drag handle but the list item is dragged. The remaining list items are the dropzone. This all works great until placed into a container with limited height and scrolling is necessary. After scrolling, the item isn't dropped in the right place. 

I added `interact.dynamicDrop(true)` which did help with the cursor/scroll offset but it still isn't getting the right dropzone. 

I've put together a simplified JSFiddle: https://jsfiddle.net/wrgjozh0/6/

Thanks!

**Comment by kgibb** [comment] 2017-03-01 09:41
Any update on this?

**Comment by martinfitzg** [comment] 2017-03-07 01:16
Working on a product at the moment that is using interact.js and I believe we are seeing the same issue.  Would this be a limitation of interact.is or is there an issue here?

**Comment by taye** [comment] 2017-04-13 00:11
This is currently a limitation of interact.js. I'm thinking about how to fix it and closing this as a duplicate of #468.

**Closed by taye** 2017-04-13 00:11 UTC
