### ISSUE TITLE
npm i throw error

### ISSUE THREAD

**Issue by merfais** [taye/interact.js#889] opened 2021-03-03 07:41 UTC
If you have questions about the [API](http://interactjs.io/api) that aren't answered in the [docs](http://interactjs.io/docs) or [FAQ](http://interactjs.io/docs/faq), try asking in the [Gitter chatroom](https://gitter.im/taye/interact.js) or on [Stackoverflow](https://stackoverflow.com/questions/tagged/interact.js).

If you've found something that looks like a bug, include a link to a minimal demo on [JSFilddle](https://jsfiddle.net), [Codepen](https://codepen.io) with instructions to reproduce the bug with and roughly follow the following issue description format:

### Expected behavior
install latest version success

### Actual behavior
```
$ npm i -d @interactjs/interactjs

npm info it worked if it ends with ok
npm info using npm@6.14.4
npm info using node@v12.18.0
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2finteractjs 1118ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs/interactjs/-/interactjs-1.10.5.tgz 124ms
npm timing stage:loadCurrentTree Completed in 1331ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 30ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2factions 220ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2fclone 323ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2ffeedback 369ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs/actions/-/actions-1.10.5.tgz 153ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2farrange 383ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2fdev-tools 434ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2finteract 449ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2fauto-start 494ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2fmulti-target 128ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2foffset 129ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2fauto-scroll 523ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2fmodifiers 200ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs/interact/-/interact-1.10.5.tgz 101ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs/dev-tools/-/dev-tools-1.10.5.tgz 120ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2finertia 557ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs/auto-start/-/auto-start-1.10.5.tgz 109ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs/offset/-/offset-1.10.5.tgz 113ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs/modifiers/-/modifiers-1.10.5.tgz 107ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2fpointer-events 251ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2freact 141ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs/inertia/-/inertia-1.10.5.tgz 99ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2fcore 665ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs/auto-scroll/-/auto-scroll-1.10.5.tgz 161ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2freflow 154ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2fvue 123ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs%2futils 171ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs/pointer-events/-/pointer-events-1.10.5.tgz 144ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs/core/-/core-1.10.5.tgz 122ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs/reflow/-/reflow-1.10.5.tgz 107ms
npm http fetch GET 200 https://registry.npmjs.org/@interactjs/utils/-/utils-1.10.5.tgz 144ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 2272ms
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @interactjs/clone@1.10.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@interactjs/interactjs'
npm ERR! notarget
npm timing npm Completed in 2911ms

```

### System configuration
**interact.js version**:
**Browser name and version**:
**Operating System**:

**Comment by rahulshinde11** [comment] 2021-03-03 07:45
Same issue here
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @interactjs/clone@1.10.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@interactjs/interactjs'
npm ERR! notarget 


```

**Comment by bisu8018** [comment] 2021-03-03 08:52
same here.
@interactjs/clone@1.10.5.
@interactjs/arrange@1.10.5.

**Comment by AnonymousArthur** [comment] 2021-03-03 08:58
Duplicate of #889

**Comment by MadalinaCi** [comment] 2021-03-03 12:03
same here : @interactjs/react@1.10.5

**Comment by viniciusbarth** [comment] 2021-03-03 15:08
same problem here:

![image](https://user-images.githubusercontent.com/29419425/109825627-c4ef2b80-7c18-11eb-8ff5-b1657dc5f476.png)

we are trying to find a lib that uses **interactjs** to adjust for the version, but without success.

**Comment by RenanRossiDias** [comment] 2021-03-03 15:18
Same with @interactjs/arrange@1.10.5

We're grounded due to this issue.

**Comment by rahulshinde11** [comment] 2021-03-03 15:53
for quick fix, manually install in your project
`npm i @interactjs/interactjs@1.10.3`

**Comment by Meshiest** [comment] 2021-03-03 18:20
pretty sure these dependencies became "pro" features

https://github.com/taye/interact.js/blob/main/scripts/bin/_add_plugin_indexes.js#L18
https://github.com/taye/interact.js/blob/main/scripts/utils.js#L103

**Comment by TheMink97** [comment] 2021-03-03 18:34
> pretty sure these dependencies became "pro" features
> 
> https://github.com/taye/interact.js/blob/main/scripts/bin/_add_plugin_indexes.js#L18
> https://github.com/taye/interact.js/blob/main/scripts/utils.js#L103

Wow, that's a really scummy, especially that the devs pull this after people have been using this in their work. If they need money, they should've have opened up a Patreon and I would've have paid and supported them. But this.. this was a dick move by the devs.

**Comment by rahulshinde11** [comment] 2021-03-03 18:58
@taye  I'm guessing  CI/CD couldn't push the child packages to npm somehow?

**Comment by taye** [comment] 2021-03-03 19:03
@Meshiest The packages that were removed from npm contained only non functional stubs: https://github.com/taye/interact.js/blob/v1.10.3/packages/%40interactjs/vue/plugin.ts. No features have been removed and I don't plan on moving features from free to a paid tier.

>Wow, that's really scummy, especially that the devs pull this after people have been using this in their work. If they need money, they should've have opened up a Patreon and I would've have paid and supported them. But this.. this was a dick move by the devs.

@TheMink97 Please investigate a bit more before coming to such poor conclusions of someone's intentions.

Closing as a duplicate of #888.

**Closed by taye** 2021-03-03 19:03 UTC
