### ISSUE TITLE
Use of elementRect in resize restriction will stop the resizing

### ISSUE THREAD

**Issue by NewInGit** [taye/interact.js#484] opened 2017-01-28 14:01 UTC
I have a div, after resizing it to the edge of its parent, the div will not resize anymore. I'm using elementRect for the restriction:
```
.resizable({
    restrict:{
        restriction: 'parent',
        elementRect: { top: 0, left: 0, bottom: 1, right: 1 }
    },
    
    edges: { left: true, right: true, bottom: true, top: true }
 })
```
Here is the [fiddle](https://jsfiddle.net/coolesterman/jrcgrxp5/)

**Comment by taye** [comment] 2017-01-28 22:18
Resize restrictions are currently broken. A solution is being worked on in #455. I'm closing this issue as a duplicate of #84.

**Closed by taye** 2017-01-28 22:18 UTC
