### ISSUE TITLE
Resize cursor stays when clicking on edge of resizeable 

### ISSUE THREAD

**Issue by mauvilsa** [taye/interact.js#366] opened 2016-03-17 11:53 UTC
When clicking on the edge of a resizable, the mouse cursor changes to ns-resize and stays like that regardless of where I move the mouse. It only changes back when an event is triggered that modifies the cursor style. This can be reproduced in the resize example at http://interactjs.io/. The same behaviour is observed in the browsers I have tried: Linux (Firefox 45 and Chromium 48) and in Windows 7 (IE 11).

**Comment by taye** [comment] 2016-04-08 20:32
Duplicate of #364

**Closed by taye** 2016-04-08 20:32 UTC
