### ISSUE TITLE
Trouble getting autoScroll to work

### ISSUE THREAD

**Issue by thechrisroberts** [taye/interact.js#307] opened 2015-11-09 17:22 UTC
I'm using drag/drop to drop divs into containers. That works well, but I'm having trouble getting autoscroll working. I'm using manualStart in order to clone the element being dragged. This works well and produces the visual effect I want, but nothing I'm doing with the autoScroll setting works. No errors, just no scrolling of the page when the user reaches the top/bottom. Here's my current incarnation:

    interact(sel).draggable({
        manualStart: true,
        autoScroll: true,
        onstart: dragStart,
        onmove: dragMove,
        onend: dragEnd
    })
        .on('move', globalMove);

I've also tried setting autoScroll to an object, ie: `autoScroll: { enabled: true }` but still no dice. I'm just scrolling within the window, not a scrollable div.

**Comment by taye** [comment] 2015-11-09 21:47
What version of interact.js are you using and on which browser(s)? Can you make a small demo that reproduces the issue?

My first guess is that `<html>` or `<body>` have CSS `overflow: hidden`. Does the page have scrollbars either always or when you move the the element beyond the edge of the window?

**Comment by thechrisroberts** [comment] 2015-11-09 22:32
Using 1.2.6, but you led me to try something. Looks like it could be partly a Chrome issue - I have overflow-x: hidden which in Chrome is keeping autoscroll from working vertically, although it appears to work in Safari. If I turn off overflow-x: hidden; then autoscroll works in Chrome (which isn't a solution for me since I need overflow-x: hidden on the body).

**Comment by taye** [comment] 2015-11-11 03:46
I close this issue since the problem is the in Chrome and the CSS rules that you're using.

**Closed by taye** 2015-11-11 03:46 UTC
