### ISSUE TITLE
Script error while using gestures on iPad

### ISSUE THREAD

**Issue by DaxGama** [taye/interact.js#377] opened 2016-04-13 06:27 UTC
Error: TypeError: null is not an object (evaluating 'this.target._element')

line: if (this.pointerIds.length > 1 && **this.target**._element === this.element) {

this.target is null which causes this error

**Comment by Ladret** [comment] 2016-04-13 08:17
Hi,I got the same issue, it seems to be related to multi-touch gestures. I seem to be able to trigger it by using two fingers and doing multiple ping/zoom gestures while rotating my fingers.

It seems to trigger when the fingers are pinched together, and once triggered I need to reload to restore the touch functionality.

I've tried both the unstable and the current release.

**Comment by taye** [comment] 2016-04-13 23:17
Can you share a stack trace with the unstable version?

**Comment by andrejpavlovic** [comment] 2016-04-26 19:32
Stack trace of lastest unstable:
```
Uncaught TypeError: Cannot read property 'length' of null
fireActiveDrops @ drop.js:119
fireDropEvents @ drop.js:259
(anonymous function) @ drop.js:63
fire @ Signals.js:35
end @ Interaction.js:303
pointerUp @ Interaction.js:273
(anonymous function) @ Interaction.js:420
```

It looks like "Interaction.signals.on('stop-drag', ..." gets triggered before "fireActiveDrops".

**Comment by andrejpavlovic** [comment] 2016-04-26 20:04
So it looks like this occurs when calling unset() on a draggable item inside the ondrop callback of a dropzone. The workaround was to delay the unset() call until after ondrop callback completes using setTimeout.

**Comment by taye** [comment] 2016-08-10 09:27
This should be fixed in the unstable version.

**Closed** 2016-08-10 09:43 UTC

**Comment by wombat86** [comment] 2017-03-03 10:34
Hey, I'm getting the same error on iPhone when using gesturable and draggable on the same element. Steps to reproduce:
1. Start pinch zoom with two fingers
2. Release only ONE finger
3. Holding the second finger down, touch first finger back again

**Comment by arggh** [comment] 2017-03-14 13:05
Chiming in on this.

I get this

```
[Error] TypeError: null is not an object (evaluating 'this.target._element')
	pointerDown (modules.js:25554)
	(anonymous function) (modules.js:27319)
```

when I call `event.interaction.stop();` inside the `onstart`-function of a draggable.

**Comment by taye** [comment] 2017-04-14 13:42
@arggh `v1.3.0-alpha` has an `interaction.end()` method which will fire `[action]end` events before stopping.
