### ISSUE TITLE
Restrict resizing of elements

### ISSUE THREAD

**Issue by AlecRust** [taye/interact.js#482] opened 2017-01-24 14:27 UTC
I see there is restriction documentation on confining an element to a certain area:

http://interactjs.io/docs/restriction/#restrict

However I can't find any mention of restricting the size of an element e.g. setting a minimum size element can be scaled to?

**Comment by AlecRust** [comment] 2017-01-26 15:44
Looks like this may be added in https://github.com/taye/interact.js/pull/455.

**Comment by taye** [comment] 2017-01-27 16:32
Yes, it's planned for the next release. I don't know when that will be but I hope to get it done within the next 2 months.

Closing as a duplicate of #84.

**Closed by taye** 2017-01-27 16:32 UTC

**Comment by jithinkradhakrishnan** [comment] 2019-05-28 10:17
Can we restrict size of each item after we initiated interact resize
