### ISSUE TITLE
Installation dependency and types/index.d.ts erorr

### ISSUE THREAD

**Issue by zhangpingchuan** [taye/interact.js#880] opened 2021-01-19 07:12 UTC
BaseEvent<null>
Type 'null' does not satisfy the constraint '"drag" | "drop" | "resize" | "gesture"'.

**Comment by taye** [comment] 2021-02-06 00:57
Closing as a duplicate of #822 since that provides more info.

**Closed by taye** 2021-02-06 00:57 UTC
