### ISSUE TITLE
Elements with preserveAspectRatio do not always obey resize restrictions

### ISSUE THREAD

**Issue by doppio** [taye/interact.js#350] opened 2016-01-30 07:44 UTC
Elements with preserveAspectRatio do not always obey resize restrictions. For example, when dragging an element from the top/bottom edge, the left/right sides expand (as they should, due to the preserveAspectRatio flag), but they can exceed the bounds of the container. The element should stop scaling up if any of the edges have reached the bounds of its container.
##

**Comment by taye** [comment] 2016-04-08 20:49
Resize restrictions are [broken](https://github.com/taye/interact.js/issues/84). I don't know when I'll have time to try to fix this.

**Comment by mixn** [comment] 2019-03-28 14:23
Hey @taye, thank you for this great tool.

Any updates on this being fixed soon? 🤞 Anything that can be done to help?

Thank you so much!

**Comment by taye** [comment] 2019-07-14 02:19
Closing this issue as a duplicate of #163 as I'll try to fix the two problems together.

**Closed by taye** 2019-07-14 02:19 UTC

**Comment by mixn** [comment] 2019-07-15 08:13
Thanks on the update @taye, appreciated!

😍 @ this:

<img width="484" alt="Screenshot 2019-07-15 at 10 11 41" src="https://user-images.githubusercontent.com/672237/61202871-0f8cfe80-a6e9-11e9-97fd-c3d6903b09a4.png">
