### ISSUE TITLE
Using interact.js in a scaled and externally generated iFrame

### ISSUE THREAD

**Issue by aminta** [taye/interact.js#586] opened 2018-01-15 19:09 UTC
Hi!

I'm using interact.js in a iFrame - generated from another JS library and not present in the source - and scaled in its HTML element, the dragging works but when I drag an item downward the cursor diverges larger and larger from the item.

If I set "transform: scale(1);" to the iFrame scale it works as expected.

Here you can reproduce the problem adding i.e "transform: scale(0.5);" to the html element in iFrame: https://s.codepen.io/aminta/debug/RxYWNy/RBrOJeBmmbRM

Any hint?

Thanks!

**Comment by nikparo** [comment] 2018-01-18 11:32
Sorry but you may want to review your example, I get "This debug view expired" when trying to view it.

**Comment by taye** [comment] 2018-03-20 10:06
Duplicate of #137

**Closed by taye** 2018-03-20 10:06 UTC
