### ISSUE TITLE
Add dynamicDrop to index.d.ts for typescript useability

### ISSUE THREAD

**Issue by rmiller-sgntr** [taye/interact.js#658] opened 2018-08-24 12:02 UTC
### Expected behavior
Dynamically added elements (e.g. rendered under Angular's *ngFor) should interact if created while dragging.

### Actual behavior
Dropzones do not interact. Since the `dynamicDrop` is not declared in `index.d.ts` , it is not usable with typescript (TSLint fails).

### Resolution
Add the `dynamicDrop (boolean) : any` to `interface InteractStatic` in `index.d.ts` like so:
```
interface InteractStatic {
    ( el: DOMElement | CSSSelector, opts?: InteractOptions ): Interactable
    on ( opt: OnEvent | OnEventFunctions, listener?: Listener ) : Interactable
    supportsTouch () : boolean
    supportsPointerEvent () : boolean
    stop ( event: any ) : InteractStatic
    pointerMoveTolerance ( tol?: number ) : number | InteractStatic
    // TODO
    isSet ( any ) : any
    off ( any ) : any
    debug ( any ) : any
    addDocument ( any ) : any
    removeDocument ( any ) : any
    dynamicDrop (boolean) : any
  }
```

Thanks in advance.

**Comment by taye** [comment] 2019-01-28 01:22
Duplicate of #623

**Closed by taye** 2019-01-28 01:22 UTC
