### ISSUE TITLE
index.d.ts is not complete

### ISSUE THREAD

**Issue by VitalySlyearenko** [taye/interact.js#604] opened 2018-02-13 12:36 UTC
Hello, the index.d.ts is not complete so after update the package we have got some errors:
1. Interactable interface doesn't contains all functions described in http://interactjs.io/api/Interactable.html (e.g. we are using function 'unset' but now have error from typescript compiler)
2. dropzone ( opt: DropZoneOptions ) doesn't contains boolean type (despite that fact it is in the docs http://interactjs.io/api/Interactable.html#dropzone and should be boolean | DropZoneOptions )

**Comment by taye** [comment] 2018-02-13 12:52
Duplicate of #572

**Closed by taye** 2018-02-13 12:52 UTC
