### ISSUE TITLE
webkitMovement is deprecated: use movement instead

### ISSUE THREAD

**Issue by baptistebriel** [taye/interact.js#278] opened 2015-09-08 12:25 UTC
Hi,
I get theses warnings when using interact.js:

`'webkitMovementX' is deprecated. Please use 'movementX' instead.`
`'webkitMovementY' is deprecated. Please use 'movementY' instead.`

but couldn't find the line in the source, any ideas?
thanks!

**Comment by taye** [comment] 2015-09-08 12:29
Duplicate of #277.

https://github.com/taye/interact.js/blob/0b94aace680199b6261989363dfc102532c49a5d/interact.js#L2763.

**Closed by taye** 2015-09-08 12:29 UTC
