### ISSUE TITLE
Mouse alignment when using transform to zoom draggable objects.

### ISSUE THREAD

**Issue by Fantastitech** [taye/interact.js#609] opened 2018-03-07 20:53 UTC
I'm creating a digital signage editor and server and I'm vetting interact.js for the frontend editor. My requirement is a WYSIWYG editor to drag/drop/resize HTML elements that exist in 1080P, scaled down to a manageable viewport. For this I'm using basic CSS transforms and a wrapper div. The wrapper is the size of the viewport and the actual editor is 1080P scaled down to the viewport size to maintain literal positions when saving element locations to the server so the content will look exactly the same full-screen on a 1080P display as it will in the editor, just zoomed out. I hope I'm explaining that well.

What _should_ happen for my use-case is if the mouse pointer is inside an element with draggable objects, the objects should stay under the actual position of the cursor.

What I'm seeing happening is the draggable elements are moving to scale with the zoomed out element while the mouse is moving the full distance in pixels on the monitor.

I created a recording of what it looks like here: https://gfycat.com/gifs/detail/DisgustingOrdinaryGrebe

Here is a jsfiddle of my demo: https://jsfiddle.net/xswnpt3w/

### System configuration
**interact.js version**: 1.3.3
**Browser name and version**: Chrome 64
**Operating System**: Windows 10

**Comment by taye** [comment] 2018-03-20 08:06
Duplicate of #137

**Closed by taye** 2018-03-20 08:06 UTC
