### ISSUE TITLE
Mobile issue with dragging

### ISSUE THREAD

**Issue by MasterBroki** [taye/interact.js#656] opened 2018-08-16 15:43 UTC
Here is a codepen:
https://codepen.io/masterbroki/pen/mjZxmj

### Expected behavior

Should simply drag and drop on mobile

### Actual behavior

On desktop, no problem, but on mobile it drags for a bit and then stops. It can be reproduced with the mobile view in chrome on the desktop. The onend event gets fired

### System configuration
**interact.js version**: 1.3.4
**Browser name and version**: Chrome 67.0.3396.99 and Chrome mobile 68.0.3440.91
**Operating System**: MacOS High Sierra 10.13.5 and Samsung Galaxy A5 with Oreo

**Comment by gurupras** [comment] 2018-08-23 12:07
I'm facing this issue as well.
I tried to check the events that were being fired while attempting to drag and here's what I got:
```
[interact]: el=self-video evt=down
[interact]: el=self-video evt=move
[interact]: el=self-video evt=dragstart
[interact]: el=self-video evt=dragmove
[interact]: el=self-video evt=move
[interact]: el=self-video evt=dragmove
[interact]: el=self-video evt=cancel
[interact]: el=self-video evt=dragend
```
All of this when I was still attempting to drag the element across the screen.
So, I guess the problem is with whatever is causing the `cancel` and `dragend` prematurely.

**Comment by gurupras** [comment] 2018-08-23 12:15
Okay, it looks like this is a duplicate of #595. The solution posted there works for me on Chrome on Android

**Comment by MasterBroki** [comment] 2018-08-25 18:36
Great! Unfortunatly I had to move to another library (business needed results fast). I hope it's gonna help someone else, thanks!

**Comment by Joeao** [comment] 2018-08-26 04:01
@masterbroki Issue can be closed then, right?

**Comment by MasterBroki** [comment] 2018-08-26 16:47
I guess, if the other solution works

**Comment by Joeao** [comment] 2018-08-27 00:25
Go ahead

**Closed** 2018-09-26 21:18 UTC

**Comment by FabianHummel** [comment] 2025-02-09 17:44
the css rule "touch-action": "none" solves this issue
