### ISSUE TITLE
Move cursor is not reset to normal after click on draggable

### ISSUE THREAD

**Issue by andriy-kudrya** [taye/interact.js#390] opened 2016-05-17 10:51 UTC
Reproduced on Microsoft Edge and Google Chrome
Reproduced on own project and on [http://interactjs.io/](http://interactjs.io/)

interact.js version:
- 1.2.6

Steps to reproduce:
- navigate to [http://interactjs.io/](http://interactjs.io/)
- within first dragging sample just click once on rectangle with text "You can drag one element"
- move cursor out of that element

Result:
- "move" cursor remains on any part of page (debuger shows it is set in style attribute of html element)

It may be required a few tries to reproduce that behavior #

**Comment by jeffrmatthews** [comment] 2016-05-26 15:37
I also had this issue on my interact 1.2.6 build and was able to remedy by adding {cursor:move;} style to the interact element. Cursor no longer keeps the 'move' style after clicking.

**Comment by andriy-kudrya** [comment] 2016-05-26 16:29
@jeffrmatthews: although I've switched to html5 api for now, thanx for workaround )

**Comment by taye** [comment] 2016-08-10 11:25
Duplicate of https://github.com/taye/interact.js/issues/364.

**Closed by taye** 2016-08-10 11:25 UTC
