### ISSUE TITLE
preventDefault does not work

### ISSUE THREAD

**Issue by ArminMueller** [taye/interact.js#514] opened 2017-05-26 07:45 UTC
Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

System configuration

interact.js version: 1.2.8
Browser name and version: Chrome 59

**Comment by taye** [comment] 2017-06-01 08:08
Duplicate of #512

**Closed by taye** 2017-06-01 08:08 UTC
