### ISSUE TITLE
Transform scale and restrict

### ISSUE THREAD

**Issue by youssefdetovernickr** [taye/interact.js#165] opened 2015-03-14 18:38 UTC
If you use transform scale on a div and place a draggable object in it, with restriction the parent, try dragging your object: it goes way slower and moving 100 pixels to the right doesn't mean 100 pixels to the right, it means movement*scale of the parent.

Also, it restricts your movements too. If you grab the object and drag it as far as you could, it stops at some point as it thinks you've reached the edge already. However, if you then re-grab the object it suddenly can go further again, until at some point the script thinks you're at the edge of the parent again.

**Comment by taye** [comment] 2015-03-14 18:57
This is a duplicate of issue #137.

**Closed by taye** 2015-03-14 18:57 UTC
