### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by webdeveloper001** [taye/interact.js#821] opened 2020-05-18 09:59 UTC
Uncaught TypeError: Super expression must either be null or a function
    at interact.min.js:824
    at interact.min.js:823
    at interact.min.js:822
    at Object.<anonymous> (interact.min.js:3)
    at p ((index):1)
    at Object.<anonymous> (Item.js:12)
    at p ((index):1)
    at Object.<anonymous> (Items.js:12)
    at p ((index):1)
    at Object.<anonymous> (Timeline.js:14)

I am using react-calendar-timeline on my project.
I could notice that this module use interact.js as its dependency.
The above issue is the one I got on my prod mode.
It's working on dev mode.

Version 1.3.4

Please give me advice on this issue.

**Comment by taye** [comment] 2020-06-01 21:18
Duplicate of #818

**Closed by taye** 2020-06-01 21:18 UTC
Labels: wontfix
