### ISSUE TITLE
restrict to parent doesn´t work when `preserveAspectRatio = true` in `.resizable`

### ISSUE THREAD

**Issue by sydev** [taye/interact.js#721] opened 2019-05-21 12:20 UTC
### Expected behavior
The resizable element should not overflow its parent

### Actual behavior
The resizable element overflows its parent on the bottom side

### Demo
https://jsfiddle.net/deurpt6h/

### System configuration
**interact.js version**: 1.4.1
**Browser name and version**: Chrome 74
**Operating System**: OSX 10.14.4

**Comment by taye** [comment] 2019-06-03 13:10
Duplicate of #350

**Closed by taye** 2019-06-03 13:10 UTC
