### ISSUE TITLE
1.3.0 Alpha 2 cancels element clicks events on mobile when attached.

### ISSUE THREAD

**Issue by timothyallan** [taye/interact.js#527] opened 2017-06-25 05:15 UTC
### Expected behavior
Should see a click event on both mobile + desktop.

### Actual behavior
Only see the click event on desktop, until interact is removed, then click events occur on both.

### System configuration
1.3.0 alpha2
iOS 10 and Chrome latest macOs

https://jsfiddle.net/k2t7h13b/10/

**Comment by taye** [comment] 2017-06-25 09:52
Duplicate of #58. Safari doesn't support the `touch-action` CSS property so there's no way to prevent scrolling without also preventing click events. I think the best solution is to use interact.js' "tap" event instead of "click".

**Closed by taye** 2017-06-25 09:52 UTC
