### ISSUE TITLE
resize elementrect prevents me from resizing a full width div

### ISSUE THREAD

**Issue by munkex** [taye/interact.js#256] opened 2015-08-14 09:16 UTC
Hey,
I have tried to figure out what im doing wrong here but i can't seem to figure it out,
i have tried to make a fiddle to show you whats happening

http://jsfiddle.net/5xnykms5/6/

I have the red box wich have been set to 500 pixel same as the parent container.
And a green box wich is set to 300 pixel.

The problem is that if the width gets same as parent i wont be able to resize it smaller again
(both if i resize the green box to 500 pixel and then try to resize it smaller again and the red box wich is 500 pixel)
And at the same time i should not be able to resize the boxes so they are wider or higher than the parent container.

**Comment by taye** [comment] 2015-08-16 11:30
Resize restrictions (and snapping) are broken. See issues #84, #163. The only solution for now is to implement your own restriction in your resize move listener.

**Comment by taye** [comment] 2015-11-21 01:41
Closing as a duplicate of #84

**Closed by taye** 2015-11-21 01:41 UTC
