### ISSUE TITLE
custom build version

### ISSUE THREAD

**Issue by littlee** [taye/interact.js#809] opened 2020-04-17 03:27 UTC
the whole `interact.min.js` is about `160kB`

https://unpkg.com/browse/interactjs@1.9.9/dist/

It might be overkill if I only use a few of APIs, is there a way to make a custom build version to reduce the file size ?

**Comment by taye** [comment] 2020-04-18 11:39
Duplicate of #800

**Closed by taye** 2020-04-18 11:39 UTC
